#include <stdio.h>
#include <stdlib.h>
#include "Headers/questao01.h"
#include "questao01.c"
// #include "Headers/questao02.h"
// #include "questao02.c"
// #include "Headers/questao03.h"
// #include "questao03.c"
// #include "Headers/questao04.h"
// #include "questao04.c"
// #include "Headers/questao05.h"
// #include "questao05.c"
// #include "Headers/questao06.h"
// #include "questao06.c"
// #include "Headers/questao07.h"
// #include "questao07.c"
// #include "Headers/questao08.h"
// #include "questao08.c"
// #include "Headers/questao09.h"
// #include "questao09.c"
// #include "Headers/questao10.h"
// #include "questao10.c"
// #include "Headers/questao11.h"
// #include "questao11.c"
// #include "Headers/questao12.h"
// #include "questao12.c"
// #include "Headers/questao13.h"
// #include "questao13.c"
// #include "Headers/questao14.h"
// #include "questao14.c"
// #include "Headers/questao15.h"
// #include "questao15.c"
// #include "Headers/questao16.h"
// #include "questao16.c"
// #include "Headers/questao17.h"
// #include "questao17.c"
// #include "Headers/questao18.h"
// #include "questao18.c"
// #include "Headers/questao19.h"
// #include "questao19.c"
// #include "Headers/questao20.h"
// #include "questao20.c"
// #include "Headers/questao21.h"
// #include "questao21.c"
// #include "Headers/questao22.h"
// #include "questao22.c"
// #include "Headers/questao23.h"
// #include "questao23.c"
// #include "Headers/questao24.h"
// #include "questao24.c"

int main()
{

    questao01();

    return 0;
}